#=
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
=#

function calc()
  fibs = [1, 1]
  while fibs[end] <= 4_000_000
    push!(fibs, fibs[end] + fibs[end-1])
  end
  filter(x -> iseven(x) && x < 4_000_000, fibs) |> sum |> println
end
@time calc()
