#=
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
=#
function pent(x)
  div(x*(3x-1),2)
end

function ispent(x)
  n = (sqrt(24x+1)+1)/6
  return n == int(n) && n > 0
end

function calc()
  i = 0
  pentagonals = Int64[]
  while true
    i += 1
    p = pent(i)
    for j in pentagonals
      diff = abs(p-j)
      if ispent(diff)
        intsum = p + j
        if ispent(intsum)
          return diff
        end
      end
    end
    push!(pentagonals, p)
  end
end
@time println(calc())
